version: "3.8"

services:
    front:
        build: ./front
        ports:
            - 8000:80
        environment:
            BACK_URL: http://localhost:8001
    back:
        build: ./back
        ports:
            - 8001:8001
        environment:
            OCSP_URL: http://ocsp:8002
            JWT_URL: https://jwt:1443/api/v1.0/auth
    ocsp:
        build: ./ocsp
        ports:
            - 8002:8002
        volumes:
            - ocsp-db:/usr/src/app/db
        environment:
            DB: /usr/src/app/db/revoked.sqlite
    jwt:
        image: docker.sunet.se/auth-server-poc:latest
        ports:
            - 8003:1443
        volumes:
            - jwt-cert:/opt/auth-server-poc/cert
            - jwt-user-db:/opt/auth-server-poc/userdb
volumes:
    ocsp-db:
    jwt-cert:
    jwt-user-db:
